controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    # Lista de controladores
    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# Configuración del controlador de dirección Ackermann
ackermann_steering_controller:
  ros__parameters:
    # Ruedas de tracción (delanteras)
    front_wheels_names: ["front_left_hinge_to_wheel", "front_right_hinge_to_wheel"]
    
    # Ruedas traseras (solo para odometría)
    rear_wheels_names: ["base_to_back_left_wheel", "base_to_back_right_wheel"]
    
    # Juntas de dirección
    front_steering_names: ["base_to_front_left_hinge", "base_to_front_right_hinge"]
    
    # Parámetros del vehículo (basados en tu XACRO)
    wheelbase: 0.24    # Distancia entre ejes
    front_wheel_track: 0.20   # Distancia entre ruedas delanteras (wheel_length + width = 0.04 + 0.16)
    rear_wheel_track: 0.20    # Distancia entre ruedas traseras
    wheel_radius: 0.04        # Radio de las ruedas
    
    # Configuración de tópicos
    reference_timeout: 2.0
    front_steering: true
    
    # Publicar odometría
    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: ego_racecar/base_link
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    
    # Habilitar odometría
    enable_odom_tf: true
    
    # Comandos de velocidad
    linear:
      x:
        has_velocity_limits: true
        has_acceleration_limits: true
        max_velocity: 3.0         # m/s (reducido para F1Tenth)
        min_velocity: -3.0        # m/s  
        max_acceleration: 1.5     # m/s^2
        min_acceleration: -1.5    # m/s^2
    
    angular:
      z:
        has_velocity_limits: true
        has_acceleration_limits: true
        max_velocity: 2.0         # rad/s
        min_velocity: -2.0        # rad/s
        max_acceleration: 1.0     # rad/s^2
        min_acceleration: -1.0    # rad/s^2

# Configuración del publicador de estados de juntas
joint_state_broadcaster:
  ros__parameters:
    joints:
      - front_left_hinge_to_wheel
      - front_right_hinge_to_wheel  
      - base_to_back_left_wheel
      - base_to_back_right_wheel
      - base_to_front_left_hinge
      - base_to_front_right_hinge
    
    interfaces:
      - position
      - velocity