controller_manager:
  ros__parameters:
    update_rate: 50  # Reducido para debug

    # Solo joint_state_broadcaster primero
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

# Configuración mínima para joint_state_broadcaster
joint_state_broadcaster:
  ros__parameters:
    joints:
      - base_to_back_left_wheel
      - base_to_back_right_wheel
      - front_left_hinge_to_wheel
      - front_right_hinge_to_wheel
      - base_to_front_left_hinge
      - base_to_front_right_hinge
    interfaces:
      - position
      - velocity

# COMENTADO TEMPORALMENTE PARA DEBUG:
# controller_manager:
#   ros__parameters:
#     ackermann_steering_controller:
#       type: ackermann_steering_controller/AckermannSteeringController

# ackermann_steering_controller:
#   ros__parameters:
#     front_wheels_names: ["front_left_hinge_to_wheel", "front_right_hinge_to_wheel"]
#     rear_wheels_names: ["base_to_back_left_wheel", "base_to_back_right_wheel"]
#     front_steering_names: ["base_to_front_left_hinge", "base_to_front_right_hinge"]
#     wheelbase: 0.24
#     front_wheel_track: 0.20
#     rear_wheel_track: 0.20
#     wheel_radius: 0.04
#     reference_timeout: 2.0
#     front_steering: true
#     publish_rate: 50.0
#     odom_frame_id: odom
#     base_frame_id: ego_racecar/base_link
#     enable_odom_tf: true