gazebo:
  ros__parameters:
    publish_rate: 400.0

physics:
  ros__parameters:
    ode:
      solver:
        type: "quick"
        iters: 50
        sor: 1.4
      constraints:
        cfm: 0.0
        erp: 0.2
        contact_max_correcting_vel: 0.1
        contact_surface_layer: 0.0